### ISSUE TITLE
hsoPro Failed to download image

### ISSUE THREAD

**Issue by vnwnv** [mamoe/mirai-plugins#4]
无法下载图像，输入keyword无反应
加载成功
09:37:27 [INFO] [hsoPro] 本地图片版本1.0.0 from https://api.lolicon.app
 09:37:27 [INFO] [hsoPro] Normal * 658
 09:37:27 [INFO] [hsoPro] R18    * 497
 09:37:27 [INFO] [hsoPro] hso插件已加载

随后报错，情况如下
[ERROR] [hsoPro] java.lang.IllegalStateException: Failed to download image
        at unknown.ImageFetcher$$special$$inlined$repeat$lambda$1$1$1.invokeSuspend(ImageFetcher.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

环境JDK8 JDK11
Windows10x64  CentOS7.5x64
报错相同

**Comment by Him188** [comment]
这些插件来自第三方开发者，请根据其描述的联系方式联系。若未提供，请等待其修复。mirai这个仓库只是一个汇总
